#!/bin/bash
# script that lists all documents with name starting by Holberton in the collection school

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <database_name>"
    exit 1
fi

mongo $1 <<EOF
db.school.find({ "name": { \$regex: "^Holberton", \$options: "i" } })
EOF
